repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.6
    hooks:
      - id: clang-format
        args: ["--style=LLVM"]
        files: ^c/.*\.(c|h)$

# 以下Rust用（rust内でcargoコマンド実行する）
  - repo: local
    hooks:
      # コードの整形
      - id: cargo-fmt
        name: cargo fmt (rust_lib)
        description: Format Rust code with cargo fmt
        # --manifest-path でrustフォルダ内の Cargo.toml を直接指定
        entry: cargo fmt --manifest-path rust/Cargo.toml -- --check
        language: system
        types: [rust]
        pass_filenames: false

      # 静的解析
      - id: cargo-clippy
        name: cargo clippy (rust_lib)
        description: Lint Rust code with cargo clippy
        # --manifest-path でrustフォルダ内の Cargo.toml を直接指定する
        entry: cargo clippy --manifest-path rust/Cargo.toml --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false